"""Shared loader for label-anchored overlay maps generated by scripts/build_overlay_mapping.py.

The blank harmonised templates (Portugal / Greece / Bulgaria) ship their coordinate map as a
generated <country>_overlay.json beside this module. Italy keeps a hand-tuned in-code map
(its template is a pre-filled sample needing redaction, so positions were set by hand).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict

COUNTRIES_DIR = Path(__file__).resolve().parent


def load_overlay_map(country: str) -> Dict[str, Dict[str, Any]]:
    path = COUNTRIES_DIR / f"{country}_overlay.json"
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return {str(k): v for k, v in data.items() if isinstance(v, dict)}
