"""Greece Schengen visa form (assets/greece_schengen_form.pdf) — blank flat PDF, overlay.

Coordinate map is generated by scripts/build_overlay_mapping.py (label-anchored) into
greece_overlay.json. Blank template -> no redaction. Verify with render_overlay_preview.py.
"""

from multi_country_fill import CountryConfig, register_country
from ._overlay_loader import load_overlay_map

register_country(
    "greece",
    CountryConfig(
        template="greece_schengen_form.pdf",
        text_map={},
        checkbox_map={},
        engine="overlay",
        overlay_map=load_overlay_map("greece"),
    ),
)
