"""Italy Schengen visa form — blank Consulate General of Italy harmonised template
(assets/italy_conslagos.pdf, Vers. 06/2024), overlay.

The client-provided Italy sample was a pre-FILLED PDF; redacting its baked-in values corrupted the
form's own printed labels. The generic English harmonised copy (italy_ambriad.pdf) has fragmented
text that defeats label anchoring. We therefore fill a BLANK Consulate General of Italy harmonised
form with the shared rect-based overlay engine, so labels are never touched.

Coordinate map is generated by scripts/build_overlay_mapping.py (cell-containment) into
italy_overlay.json. Verify with scripts/render_overlay_preview.py italy.
"""

from multi_country_fill import CountryConfig, register_country
from ._overlay_loader import load_overlay_map

register_country(
    "italy",
    CountryConfig(
        template="italy_conslagos.pdf",
        text_map={},
        checkbox_map={},
        engine="overlay",
        overlay_map=load_overlay_map("italy"),
    ),
)
