"""Portugal Schengen visa form (assets/portugal_schengen_form.pdf) — blank flat PDF, overlay.

Coordinate map is generated by scripts/build_overlay_mapping.py (label-anchored, page-agnostic,
marks the sex/marital/entries/passport/purpose/residence/all-expenses checkboxes) into
portugal_overlay.json. Blank template -> plain insert, nothing to redact.
Verify with scripts/render_overlay_preview.py.
"""

from multi_country_fill import CountryConfig, register_country
from ._overlay_loader import load_overlay_map

register_country(
    "portugal",
    CountryConfig(
        template="portugal_schengen_form.pdf",
        text_map={},
        checkbox_map={},
        engine="overlay",
        overlay_map=load_overlay_map("portugal"),
    ),
)
